import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { db } from "@/lib/db"
import * as Pendo from "@/lib/connectors/pendo"
import * as Webflow from "@/lib/connectors/webflow"
import * as Salesforce from "@/lib/connectors/salesforce"
import * as Zendesk from "@/lib/connectors/zendesk"
import * as Contentful from "@/lib/connectors/contentful"
import * as WordPress from "@/lib/connectors/wordpress"
import * as HubSpot from "@/lib/connectors/hubspot"
import * as Jira from "@/lib/connectors/jira"
import * as Slack from "@/lib/connectors/slack"
import * as Qualtrics from "@/lib/connectors/qualtrics"
import * as Marketo from "@/lib/connectors/marketo"
import * as GoogleDrive from "@/lib/connectors/googledrive"
import * as SharePoint from "@/lib/connectors/sharepoint"
import * as GitHub from "@/lib/connectors/github"
import * as GitLab from "@/lib/connectors/gitlab"
import * as Shopify from "@/lib/connectors/shopify"
import * as Notion from "@/lib/connectors/notion"

interface PushBody {
  jobId: string
  targetLanguage: string
}

// POST /api/integrations/[connector]/push — push a completed translation back to CMS
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ connector: string }> }
) {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { connector } = await params
  const body = await req.json() as PushBody

  if (!body.jobId || !body.targetLanguage) {
    return NextResponse.json({ error: "Missing jobId or targetLanguage" }, { status: 400 })
  }

  const job = await db.translationJob.findUnique({
    where: { id: body.jobId },
    include: { tasks: { where: { targetLanguage: body.targetLanguage } } },
  })

  if (!job || (session.user.role !== "admin" && job.createdById !== session.user.id)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 })
  }

  const task = job.tasks[0]
  if (!task || task.status !== "completed") {
    return NextResponse.json({ error: "Translation not completed yet" }, { status: 400 })
  }

  let meta: Record<string, unknown> = {}
  try { meta = JSON.parse(job.integrationMeta ?? "{}") } catch { /* */ }

  const contentId = meta.contentId as string | undefined
  if (!contentId) {
    return NextResponse.json({ error: "Job has no integration content ID" }, { status: 400 })
  }

  const integration = await db.integration.findUnique({
    where: { userId_connector: { userId: session.user.id, connector } },
  })
  if (!integration) {
    return NextResponse.json({ error: "Integration not configured" }, { status: 404 })
  }

  let creds: Record<string, string> = {}
  let config: Record<string, string> = {}
  try { creds = JSON.parse(integration.credentials) } catch { /* */ }
  try { config = JSON.parse(integration.config) } catch { /* */ }

  // Extract translated strings from XLIFF.
  // Handles XLIFF 1.2 format generated by buildXliffFromTranslations:
  //   <trans-unit id="node_abc" xml:space="preserve">
  //     <source>...</source>
  //     <target state="needs-review-translation">...</target>
  //   </trans-unit>
  const xliff = task.xliffData ?? ""
  if (!xliff) {
    return NextResponse.json({ error: "No XLIFF data found for this task — translation may not have completed" }, { status: 400 })
  }
  const translations: Record<string, string> = {}
  // Match trans-unit elements (with or without namespace prefix) and capture id + target text.
  const unitRe = /(?:<[a-z-]*:?)?trans-unit\b[^>]*\bid="([^"]+)"[^>]*>[\s\S]*?<(?:[a-z-]*:)?target[^>]*>([\s\S]*?)<\/(?:[a-z-]*:)?target>/g
  let match
  while ((match = unitRe.exec(xliff)) !== null) {
    const id = match[1]
    const rawText = match[2]
      .replace(/<[^>]+>/g, "")          // strip any inline XML tags
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&apos;/g, "'")
      .trim()
    if (rawText) translations[id] = rawText
  }

  if (Object.keys(translations).length === 0) {
    return NextResponse.json({ error: "No translated strings found in XLIFF — the target elements may be empty" }, { status: 400 })
  }

  const targetLanguage = body.targetLanguage

  try {
    switch (connector) {
      case "pendo": {
        const guide = await Pendo.fetchGuide(creds.apiKey ?? "", contentId)
        await Pendo.pushTranslation(creds.apiKey ?? "", Pendo.mergeTranslationsIntoGuide(guide, translations))
        break
      }
      case "webflow": {
        if (contentId.startsWith("page:")) {
          // Pages DOM API — push translated content back to a locale.
          // contentId format: "page:{pageId}:{siteId}"
          const parts = contentId.split(":")
          const pageId = parts[1] ?? ""
          const pageSiteId = parts.slice(2).join(":") // handle any colons in siteId
          const siteId = pageSiteId || (meta.siteId as string | undefined) || config.siteId || ""

          if (!pageId) throw new Error("Invalid contentId — missing pageId")
          if (!siteId) throw new Error("Cannot determine Webflow site ID. Re-connect the integration or reconfigure the site.")

          const locales = await Webflow.listLocales(creds.apiKey ?? "", siteId)
          console.log(`[Webflow push] page=${pageId} site=${siteId} targetLang=${targetLanguage} locales=${JSON.stringify(locales.map(l => ({ tag: l.tag, id: l.id, isPrimary: l.isPrimary })))} translationKeys=${Object.keys(translations).length}`)

          // Match target language to a Webflow locale tag (exact, base, or prefix).
          // e.g. "zh-CN" matches tag "zh-CN", or "zh", or tag "zh" matching "zh-CN"
          const locale = locales.find(
            (l) => l.tag === targetLanguage
              || l.tag === targetLanguage.split("-")[0]
              || targetLanguage.startsWith(l.tag)
          )

          // Webflow Pages DOM API ALWAYS requires exactly one of:
          //   ?localeId={id}   — use locale ID from listLocales (preferred)
          //   ?locale={tag}    — use locale tag e.g. "zh-CN" (fallback)
          // This applies to both primary and secondary locales.
          let localeId: string | null = null
          let localeTag: string | undefined

          if (locale) {
            // Use the locale's ID regardless of whether it's primary or secondary.
            localeId = locale.id
          } else if (locales.length > 0) {
            // Locales exist but none matched targetLanguage — surface a clear error.
            const available = locales.map(l => `${l.displayName} (${l.tag})`).join(", ")
            throw new Error(
              `Locale "${targetLanguage}" is not configured in your Webflow site. ` +
              `Available locales: ${available}. ` +
              `Add "${targetLanguage}" in Webflow → Site Settings → Localization, then retry.`
            )
          } else {
            // listLocales returned empty (e.g. API doesn't expose locales for this plan).
            // Fall back to ?locale=<tag> which Webflow also accepts.
            localeTag = targetLanguage
            console.log(`[Webflow push] No locales from API — falling back to ?locale=${localeTag}`)
          }

          console.log(`[Webflow push] calling pushPageLocale localeId=${localeId ?? "none"} localeTag=${localeTag ?? "none"} nodes=${Object.keys(translations).length}`)
          await Webflow.pushPageLocale(creds.apiKey ?? "", siteId, pageId, localeId, translations, localeTag)
        } else {
          // CMS collection items
          const byItem: Record<string, Record<string, string>> = {}
          Object.entries(translations).forEach(([key, val]) => {
            const parts = key.match(/^item_([^_]+)_(.+)$/)
            if (parts) {
              const [, itemId, field] = parts
              byItem[itemId] = byItem[itemId] ?? {}
              byItem[itemId][field] = val
            }
          })
          const itemIds = Object.keys(byItem)
          console.log(`[Webflow push] CMS collection=${contentId} items=${itemIds.length}`)
          for (const [itemId, fields] of Object.entries(byItem)) {
            await Webflow.patchItem(creds.apiKey ?? "", contentId, itemId, fields)
          }
        }
        break
      }
      case "salesforce":
        await Salesforce.pushTranslation(creds.instanceUrl ?? config.instanceUrl ?? "", creds.accessToken ?? "", contentId, translations)
        break
      case "zendesk":
        await Zendesk.pushTranslation(creds.subdomain ?? "", creds.email ?? "", creds.apiToken ?? "", contentId, targetLanguage, translations)
        break
      case "contentful":
        await Contentful.pushTranslation(creds.spaceId ?? "", creds.accessToken ?? "", config.environmentId || "master", contentId, targetLanguage, translations)
        break
      case "wordpress":
        await WordPress.pushTranslation(creds.siteUrl ?? "", creds.username ?? "", creds.applicationPassword ?? "", contentId, targetLanguage, translations)
        break
      case "hubspot":
        await HubSpot.pushTranslation(creds.apiToken ?? "", targetLanguage, translations)
        break
      case "jira":
        await Jira.pushTranslation(creds.cloudUrl ?? "", creds.email ?? "", creds.apiToken ?? "", contentId, targetLanguage, translations)
        break
      case "slack": {
        const targetChannelId = config.channelId ?? contentId.split("::")?.[0] ?? contentId
        await Slack.pushTranslation(creds.botToken ?? "", targetChannelId, translations)
        break
      }
      case "qualtrics":
        await Qualtrics.pushTranslation(creds.apiToken ?? "", creds.dataCenter ?? "", contentId, targetLanguage, translations)
        break
      case "marketo":
        await Marketo.pushTranslation(creds.munchkinId ?? "", creds.clientId ?? "", creds.clientSecret ?? "", contentId, targetLanguage, translations)
        break
      case "googledrive":
        await GoogleDrive.pushTranslation(creds.accessToken ?? "", config.folderId || undefined, contentId, targetLanguage, translations)
        break
      case "sharepoint":
        await SharePoint.pushTranslation(creds.accessToken ?? "", contentId, targetLanguage, translations)
        break
      case "github":
        await GitHub.pushTranslation(creds.apiToken ?? "", contentId, targetLanguage, translations)
        break
      case "gitlab":
        await GitLab.pushTranslation(creds.apiToken ?? "", contentId, targetLanguage, translations)
        break
      case "shopify":
        await Shopify.pushTranslation(creds.shop ?? "", creds.accessToken ?? "", contentId, targetLanguage, translations)
        break
      case "notion":
        await Notion.pushTranslation(creds.token ?? "", contentId, targetLanguage, translations)
        break
      default:
        return NextResponse.json({ error: "Unknown connector" }, { status: 400 })
    }
  } catch (err) {
    console.error(`[push/${connector}] error pushing job=${body.jobId} lang=${body.targetLanguage}:`, (err as Error).message)
    return NextResponse.json({ error: (err as Error).message }, { status: 502 })
  }

  return NextResponse.json({ ok: true, pushedStrings: Object.keys(translations).length })
}
